# Use Ubuntu 16.04 (Xenial)
dist: xenial

sudo: false

git:
  depth: 5
  quiet: true

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - git
      - wget
      - make
      - libncurses-dev
      - flex
      - bison
      - gperf
      - python
      - python-serial
      - clang-format-9

language: cpp

jobs:
  include:
    - stage: run
      script: ./.travis.sh tx
    -
      script: ./.travis.sh rx
    -
      script: ./.travis.sh txrx
