COMPONENT_SRCDIRS := . air bluetooth config input io msp output p2p platform protocols rc rmp ui util
COMPONENT_PRIV_INCLUDEDIRS := .

# Sanity check
ifndef CONFIG_RAVEN_TX_SUPPORT
ifndef CONFIG_RAVEN_RX_SUPPORT
    $(error At least TX or RX support must be enabled)
endif
endif

RC_MODE :=

ifdef CONFIG_RAVEN_TX_SUPPORT
    CPPFLAGS += -DUSE_TX_SUPPORT
    RC_MODE := $(RC_MODE)TX
endif

ifdef CONFIG_RAVEN_FAKE_TX_INPUT
    CPPFLAGS += -DUSE_TX_FAKE_INPUT
endif

ifdef CONFIG_RAVEN_RX_SUPPORT
    CPPFLAGS += -DUSE_RX_SUPPORT
    RC_MODE := $(RC_MODE)RX
endif

ifdef CONFIG_RAVEN_SCREEN_SUPPORT
    CPPFLAGS += -DUSE_SCREEN
endif

BOARD_NAME :=

ifdef CONFIG_RAVEN_PLATFORM_ESP32_LORA_TTGO_433_SCREEN
     CPPFLAGS += -DRAVEN_PLATFORM_ESP32_LORA_TTGO_433_SCREEN
     BOARD_NAME = "ESP32+LoRa+OLED TTGO 433MHz"
endif

ifdef CONFIG_RAVEN_PLATFORM_ESP32_LORA_TTGO_433
    CPPFLAGS += -DRAVEN_PLATFORM_ESP32_LORA_TTGO_433
    BOARD_NAME = "ESP32+LoRa TTGO 433MHz"
endif

ifdef CONFIG_RAVEN_PLATFORM_ESP32_LORA_TTGO_868_915_SCREEN
     CPPFLAGS += -DRAVEN_PLATFORM_ESP32_LORA_TTGO_868_915_SCREEN
     BOARD_NAME = "ESP32+LoRa+OLED TTGO 868/915MHz"
endif

ifdef CONFIG_RAVEN_PLATFORM_ESP32_LORA_TTGO_868_915
    CPPFLAGS += -DRAVEN_PLATFORM_ESP32_LORA_TTGO_868_915
    BOARD_NAME = "ESP32+LoRa TTGO 868/915MHz"
endif

ifdef CONFIG_RAVEN_PLATFORM_ESP32_LORA_HELTEC_433_SCREEN
     CPPFLAGS += -DRAVEN_PLATFORM_ESP32_LORA_HELTEC_433_SCREEN
     BOARD_NAME = "ESP32+LoRa+OLED HELTEC 433MHz"
endif

ifdef CONFIG_RAVEN_PLATFORM_ESP32_LORA_HELTEC_433
    CPPFLAGS += -DRAVEN_PLATFORM_ESP32_LORA_HELTEC_433
    BOARD_NAME = "ESP32+LoRa HELTEC 433MHz"
endif

CPPFLAGS += -DBOARD_NAME=\"$(BOARD_NAME)\"
